2024-06-15 16:28:23,654 INFO    StreamThr :7548 [internal.py:wandb_internal():86] W&B internal server running at pid: 7548, started at: 2024-06-15 16:28:23.652887
2024-06-15 16:28:23,655 DEBUG   HandlerThread:7548 [handler.py:handle_request():146] handle_request: status
2024-06-15 16:28:23,663 INFO    WriterThread:7548 [datastore.py:open_for_write():87] open: ./wandb/run-20240615_162823-32urjw61/run-32urjw61.wandb
2024-06-15 16:28:23,664 DEBUG   SenderThread:7548 [sender.py:send():379] send: header
2024-06-15 16:28:23,696 DEBUG   SenderThread:7548 [sender.py:send():379] send: run
2024-06-15 16:28:24,507 INFO    SenderThread:7548 [dir_watcher.py:__init__():211] watching files in: ./wandb/run-20240615_162823-32urjw61/files
2024-06-15 16:28:24,508 INFO    SenderThread:7548 [sender.py:_start_run_threads():1124] run started: 32urjw61 with start time 1718449103.653544
2024-06-15 16:28:24,516 DEBUG   HandlerThread:7548 [handler.py:handle_request():146] handle_request: check_version
2024-06-15 16:28:24,517 DEBUG   SenderThread:7548 [sender.py:send_request():406] send_request: check_version
2024-06-15 16:28:24,605 DEBUG   HandlerThread:7548 [handler.py:handle_request():146] handle_request: run_start
2024-06-15 16:28:24,606 DEBUG   HandlerThread:7548 [system_info.py:__init__():26] System info init
2024-06-15 16:28:24,606 DEBUG   HandlerThread:7548 [system_info.py:__init__():41] System info init done
2024-06-15 16:28:24,606 INFO    HandlerThread:7548 [system_monitor.py:start():194] Starting system monitor
2024-06-15 16:28:24,606 INFO    SystemMonitor:7548 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-06-15 16:28:24,606 INFO    HandlerThread:7548 [system_monitor.py:probe():214] Collecting system info
2024-06-15 16:28:24,606 INFO    SystemMonitor:7548 [interfaces.py:start():190] Started cpu monitoring
2024-06-15 16:28:24,608 DEBUG   HandlerThread:7548 [system_info.py:probe():150] Probing system
2024-06-15 16:28:24,609 INFO    SystemMonitor:7548 [interfaces.py:start():190] Started disk monitoring
2024-06-15 16:28:24,609 INFO    SystemMonitor:7548 [interfaces.py:start():190] Started gpuapple monitoring
2024-06-15 16:28:24,613 INFO    SystemMonitor:7548 [interfaces.py:start():190] Started memory monitoring
2024-06-15 16:28:24,614 INFO    SystemMonitor:7548 [interfaces.py:start():190] Started network monitoring
2024-06-15 16:28:24,619 DEBUG   HandlerThread:7548 [system_info.py:_probe_git():135] Probing git
2024-06-15 16:28:24,665 DEBUG   HandlerThread:7548 [system_info.py:_probe_git():143] Probing git done
2024-06-15 16:28:24,665 DEBUG   HandlerThread:7548 [system_info.py:probe():198] Probing system done
2024-06-15 16:28:24,665 DEBUG   HandlerThread:7548 [system_monitor.py:probe():223] {'os': 'macOS-14.5-arm64-arm-64bit', 'python': '3.8.19', 'heartbeatAt': '2024-06-15T10:58:24.608265', 'startedAt': '2024-06-15T10:58:23.641355', 'docker': None, 'cuda': None, 'args': ('--data_set', 'ode'), 'state': 'running', 'program': 'run.py', 'codePathLocal': 'run.py', 'codePath': 'run.py', 'git': {'remote': 'https://github.com/OATML/non-parametric-transformers.git', 'commit': 'a399360c4ac953eac3149692918df12fafee66e0'}, 'email': None, 'root': '/Users/devu/PycharmProjects/non-parametric-transformers', 'host': 'Devanshus-MacBook-Air.local', 'username': 'devu', 'executable': '/Users/devu/anaconda3/envs/npt/bin/python', 'cpu_count': 8, 'cpu_count_logical': 8, 'cpu_freq': {'current': 3204, 'min': 600, 'max': 3204}, 'cpu_freq_per_core': [{'current': 3204, 'min': 600, 'max': 3204}], 'disk': {'/': {'total': 228.27386474609375, 'used': 9.55832290649414}}, 'gpuapple': {'type': 'arm', 'vendor': 'Apple'}, 'memory': {'total': 8.0}}
2024-06-15 16:28:24,665 INFO    HandlerThread:7548 [system_monitor.py:probe():224] Finished collecting system info
2024-06-15 16:28:24,665 INFO    HandlerThread:7548 [system_monitor.py:probe():227] Publishing system info
2024-06-15 16:28:24,665 DEBUG   HandlerThread:7548 [system_info.py:_save_conda():207] Saving list of conda packages installed into the current environment
2024-06-15 16:28:25,509 INFO    Thread-12 :7548 [dir_watcher.py:_on_file_created():271] file/dir created: ./wandb/run-20240615_162823-32urjw61/files/conda-environment.yaml
2024-06-15 16:44:29,866 ERROR   HandlerThread:7548 [system_info.py:_save_conda():221] Error saving conda packages: Command '['conda', 'env', 'export']' timed out after 15 seconds
Traceback (most recent call last):
  File "/Users/devu/anaconda3/envs/npt/lib/python3.8/site-packages/wandb/sdk/internal/system/system_info.py", line 214, in _save_conda
    subprocess.call(
  File "/Users/devu/anaconda3/envs/npt/lib/python3.8/subprocess.py", line 342, in call
    return p.wait(timeout=timeout)
  File "/Users/devu/anaconda3/envs/npt/lib/python3.8/subprocess.py", line 1083, in wait
    return self._wait(timeout=timeout)
  File "/Users/devu/anaconda3/envs/npt/lib/python3.8/subprocess.py", line 1814, in _wait
    raise TimeoutExpired(self.args, timeout)
subprocess.TimeoutExpired: Command '['conda', 'env', 'export']' timed out after 15 seconds
2024-06-15 16:44:29,880 DEBUG   HandlerThread:7548 [system_info.py:_save_conda():222] Saving conda packages done
2024-06-15 16:44:29,882 INFO    HandlerThread:7548 [system_monitor.py:probe():229] Finished publishing system info
2024-06-15 16:44:29,901 DEBUG   HandlerThread:7548 [handler.py:handle_request():146] handle_request: keepalive
2024-06-15 16:44:29,901 DEBUG   HandlerThread:7548 [handler.py:handle_request():146] handle_request: status_report
2024-06-15 16:44:29,903 DEBUG   SenderThread:7548 [sender.py:send():379] send: files
2024-06-15 16:44:29,903 INFO    SenderThread:7548 [sender.py:_save_file():1390] saving file wandb-metadata.json with policy now
2024-06-15 16:44:30,056 WARNING FileStreamThread:7548 [file_stream.py:request_with_retry():687] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/non-param-transformers/default/32urjw61/file_stream (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x1167a0a30>: Failed to resolve 'api.wandb.ai' ([Errno 8] nodename nor servname provided, or not known)")). func: functools.partial(<bound method Session.post of <requests.sessions.Session object at 0x116553220>>, timeout=180.0), args: ('https://api.wandb.ai/files/non-param-transformers/default/32urjw61/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2024-06-15 16:44:30,194 DEBUG   HandlerThread:7548 [handler.py:handle_request():146] handle_request: python_packages
2024-06-15 16:44:30,194 DEBUG   SenderThread:7548 [sender.py:send_request():406] send_request: python_packages
2024-06-15 16:44:30,222 DEBUG   HandlerThread:7548 [handler.py:handle_request():146] handle_request: internal_messages
2024-06-15 16:44:30,222 DEBUG   HandlerThread:7548 [handler.py:handle_request():146] handle_request: stop_status
2024-06-15 16:44:30,222 DEBUG   SenderThread:7548 [sender.py:send_request():406] send_request: stop_status
2024-06-15 16:44:30,882 INFO    Thread-12 :7548 [dir_watcher.py:_on_file_created():271] file/dir created: ./wandb/run-20240615_162823-32urjw61/files/requirements.txt
2024-06-15 16:44:30,883 INFO    Thread-12 :7548 [dir_watcher.py:_on_file_created():271] file/dir created: ./wandb/run-20240615_162823-32urjw61/files/wandb-metadata.json
2024-06-15 16:44:32,188 WARNING FileStreamThread:7548 [file_stream.py:request_with_retry():687] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/non-param-transformers/default/32urjw61/file_stream (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x1167104c0>: Failed to resolve 'api.wandb.ai' ([Errno 8] nodename nor servname provided, or not known)")). func: functools.partial(<bound method Session.post of <requests.sessions.Session object at 0x116553220>>, timeout=180.0), args: ('https://api.wandb.ai/files/non-param-transformers/default/32urjw61/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2024-06-15 16:44:32,978 DEBUG   HandlerThread:7548 [handler.py:handle_request():146] handle_request: poll_exit
2024-06-15 16:44:33,605 INFO    SenderThread:7548 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/Users/devu/anaconda3/envs/npt/lib/python3.8/site-packages/urllib3/connection.py", line 203, in _new_conn
    sock = connection.create_connection(
  File "/Users/devu/anaconda3/envs/npt/lib/python3.8/site-packages/urllib3/util/connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/Users/devu/anaconda3/envs/npt/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/devu/anaconda3/envs/npt/lib/python3.8/site-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "/Users/devu/anaconda3/envs/npt/lib/python3.8/site-packages/urllib3/connectionpool.py", line 491, in _make_request
    raise new_e
  File "/Users/devu/anaconda3/envs/npt/lib/python3.8/site-packages/urllib3/connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "/Users/devu/anaconda3/envs/npt/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1096, in _validate_conn
    conn.connect()
  File "/Users/devu/anaconda3/envs/npt/lib/python3.8/site-packages/urllib3/connection.py", line 611, in connect
    self.sock = sock = self._new_conn()
  File "/Users/devu/anaconda3/envs/npt/lib/python3.8/site-packages/urllib3/connection.py", line 210, in _new_conn
    raise NameResolutionError(self.host, self, e) from e
urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x116710bb0>: Failed to resolve 'api.wandb.ai' ([Errno 8] nodename nor servname provided, or not known)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/devu/anaconda3/envs/npt/lib/python3.8/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/Users/devu/anaconda3/envs/npt/lib/python3.8/site-packages/urllib3/connectionpool.py", line 844, in urlopen
    retries = retries.increment(
  File "/Users/devu/anaconda3/envs/npt/lib/python3.8/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x116710bb0>: Failed to resolve 'api.wandb.ai' ([Errno 8] nodename nor servname provided, or not known)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/devu/anaconda3/envs/npt/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/Users/devu/anaconda3/envs/npt/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 369, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/Users/devu/anaconda3/envs/npt/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/Users/devu/anaconda3/envs/npt/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/Users/devu/anaconda3/envs/npt/lib/python3.8/site-packages/wandb/sdk/lib/gql_request.py", line 58, in execute
    request = self.session.post(self.url, **post_args)
  File "/Users/devu/anaconda3/envs/npt/lib/python3.8/site-packages/requests/sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "/Users/devu/anaconda3/envs/npt/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/devu/anaconda3/envs/npt/lib/python3.8/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/Users/devu/anaconda3/envs/npt/lib/python3.8/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x116710bb0>: Failed to resolve 'api.wandb.ai' ([Errno 8] nodename nor servname provided, or not known)"))
2024-06-15 16:44:35,422 INFO    wandb-upload_0:7548 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/Users/devu/anaconda3/envs/npt/lib/python3.8/site-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "/Users/devu/anaconda3/envs/npt/lib/python3.8/site-packages/urllib3/connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
  File "/Users/devu/anaconda3/envs/npt/lib/python3.8/site-packages/urllib3/connection.py", line 461, in getresponse
    httplib_response = super().getresponse()
  File "/Users/devu/anaconda3/envs/npt/lib/python3.8/http/client.py", line 1348, in getresponse
    response.begin()
  File "/Users/devu/anaconda3/envs/npt/lib/python3.8/http/client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "/Users/devu/anaconda3/envs/npt/lib/python3.8/http/client.py", line 277, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/Users/devu/anaconda3/envs/npt/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/Users/devu/anaconda3/envs/npt/lib/python3.8/ssl.py", line 1274, in recv_into
    return self.read(nbytes, buffer)
  File "/Users/devu/anaconda3/envs/npt/lib/python3.8/ssl.py", line 1132, in read
    return self._sslobj.read(len, buffer)
ConnectionResetError: [Errno 54] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/devu/anaconda3/envs/npt/lib/python3.8/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/Users/devu/anaconda3/envs/npt/lib/python3.8/site-packages/urllib3/connectionpool.py", line 844, in urlopen
    retries = retries.increment(
  File "/Users/devu/anaconda3/envs/npt/lib/python3.8/site-packages/urllib3/util/retry.py", line 470, in increment
    raise reraise(type(error), error, _stacktrace)
  File "/Users/devu/anaconda3/envs/npt/lib/python3.8/site-packages/urllib3/util/util.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "/Users/devu/anaconda3/envs/npt/lib/python3.8/site-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "/Users/devu/anaconda3/envs/npt/lib/python3.8/site-packages/urllib3/connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
  File "/Users/devu/anaconda3/envs/npt/lib/python3.8/site-packages/urllib3/connection.py", line 461, in getresponse
    httplib_response = super().getresponse()
  File "/Users/devu/anaconda3/envs/npt/lib/python3.8/http/client.py", line 1348, in getresponse
    response.begin()
  File "/Users/devu/anaconda3/envs/npt/lib/python3.8/http/client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "/Users/devu/anaconda3/envs/npt/lib/python3.8/http/client.py", line 277, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/Users/devu/anaconda3/envs/npt/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/Users/devu/anaconda3/envs/npt/lib/python3.8/ssl.py", line 1274, in recv_into
    return self.read(nbytes, buffer)
  File "/Users/devu/anaconda3/envs/npt/lib/python3.8/ssl.py", line 1132, in read
    return self._sslobj.read(len, buffer)
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/devu/anaconda3/envs/npt/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/Users/devu/anaconda3/envs/npt/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 369, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/Users/devu/anaconda3/envs/npt/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/Users/devu/anaconda3/envs/npt/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/Users/devu/anaconda3/envs/npt/lib/python3.8/site-packages/wandb/sdk/lib/gql_request.py", line 58, in execute
    request = self.session.post(self.url, **post_args)
  File "/Users/devu/anaconda3/envs/npt/lib/python3.8/site-packages/requests/sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "/Users/devu/anaconda3/envs/npt/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/devu/anaconda3/envs/npt/lib/python3.8/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/Users/devu/anaconda3/envs/npt/lib/python3.8/site-packages/requests/adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))
2024-06-15 16:44:37,911 INFO    wandb-upload_0:7548 [upload_job.py:push():131] Uploaded file /var/folders/89/yf6sr3f103jfyn0hrg_qrbnw0000gn/T/tmpq_r_qrwkwandb/tm9yt60h-wandb-metadata.json
2024-06-15 16:44:38,003 DEBUG   HandlerThread:7548 [handler.py:handle_request():146] handle_request: keepalive
2024-06-15 16:44:38,411 DEBUG   SenderThread:7548 [sender.py:send():379] send: telemetry
2024-06-15 16:44:38,411 DEBUG   HandlerThread:7548 [handler.py:handle_request():146] handle_request: status_report
2024-06-15 16:44:38,411 DEBUG   SenderThread:7548 [sender.py:send():379] send: config
2024-06-15 16:44:38,413 DEBUG   SenderThread:7548 [sender.py:send():379] send: exit
2024-06-15 16:44:38,414 INFO    SenderThread:7548 [sender.py:send_exit():586] handling exit code: 1
2024-06-15 16:44:38,414 INFO    SenderThread:7548 [sender.py:send_exit():588] handling runtime: 967
2024-06-15 16:44:38,415 INFO    SenderThread:7548 [sender.py:_save_file():1390] saving file wandb-summary.json with policy end
2024-06-15 16:44:38,415 INFO    SenderThread:7548 [sender.py:send_exit():594] send defer
2024-06-15 16:44:38,415 DEBUG   SenderThread:7548 [sender.py:send_request():406] send_request: poll_exit
2024-06-15 16:44:38,416 DEBUG   HandlerThread:7548 [handler.py:handle_request():146] handle_request: defer
2024-06-15 16:44:38,416 INFO    HandlerThread:7548 [handler.py:handle_request_defer():172] handle defer: 0
2024-06-15 16:44:38,416 DEBUG   SenderThread:7548 [sender.py:send_request():406] send_request: defer
2024-06-15 16:44:38,416 INFO    SenderThread:7548 [sender.py:send_request_defer():610] handle sender defer: 0
2024-06-15 16:44:38,416 INFO    SenderThread:7548 [sender.py:transition_state():614] send defer: 1
2024-06-15 16:44:38,416 DEBUG   HandlerThread:7548 [handler.py:handle_request():146] handle_request: defer
2024-06-15 16:44:38,416 INFO    HandlerThread:7548 [handler.py:handle_request_defer():172] handle defer: 1
2024-06-15 16:44:38,416 DEBUG   SenderThread:7548 [sender.py:send_request():406] send_request: defer
2024-06-15 16:44:38,416 INFO    SenderThread:7548 [sender.py:send_request_defer():610] handle sender defer: 1
2024-06-15 16:44:38,416 INFO    SenderThread:7548 [sender.py:transition_state():614] send defer: 2
2024-06-15 16:44:38,416 DEBUG   HandlerThread:7548 [handler.py:handle_request():146] handle_request: defer
2024-06-15 16:44:38,416 INFO    HandlerThread:7548 [handler.py:handle_request_defer():172] handle defer: 2
2024-06-15 16:44:38,416 INFO    HandlerThread:7548 [system_monitor.py:finish():203] Stopping system monitor
2024-06-15 16:44:38,416 DEBUG   SystemMonitor:7548 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2024-06-15 16:44:38,417 DEBUG   SystemMonitor:7548 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2024-06-15 16:44:38,417 INFO    HandlerThread:7548 [interfaces.py:finish():202] Joined cpu monitor
2024-06-15 16:44:38,417 DEBUG   SystemMonitor:7548 [system_monitor.py:_start():183] Publishing last batch of metrics
2024-06-15 16:44:38,417 INFO    HandlerThread:7548 [interfaces.py:finish():202] Joined disk monitor
2024-06-15 16:44:38,418 INFO    HandlerThread:7548 [interfaces.py:finish():202] Joined gpuapple monitor
2024-06-15 16:44:38,418 INFO    HandlerThread:7548 [interfaces.py:finish():202] Joined memory monitor
2024-06-15 16:44:38,418 INFO    HandlerThread:7548 [interfaces.py:finish():202] Joined network monitor
2024-06-15 16:44:38,418 DEBUG   SenderThread:7548 [sender.py:send_request():406] send_request: defer
2024-06-15 16:44:38,418 INFO    SenderThread:7548 [sender.py:send_request_defer():610] handle sender defer: 2
2024-06-15 16:44:38,418 INFO    SenderThread:7548 [sender.py:transition_state():614] send defer: 3
2024-06-15 16:44:38,418 DEBUG   SenderThread:7548 [sender.py:send():379] send: telemetry
2024-06-15 16:44:38,418 DEBUG   HandlerThread:7548 [handler.py:handle_request():146] handle_request: defer
2024-06-15 16:44:38,418 DEBUG   SenderThread:7548 [sender.py:send():379] send: stats
2024-06-15 16:44:38,418 INFO    HandlerThread:7548 [handler.py:handle_request_defer():172] handle defer: 3
2024-06-15 16:44:38,419 DEBUG   SenderThread:7548 [sender.py:send_request():406] send_request: defer
2024-06-15 16:44:38,419 INFO    SenderThread:7548 [sender.py:send_request_defer():610] handle sender defer: 3
2024-06-15 16:44:38,419 INFO    SenderThread:7548 [sender.py:transition_state():614] send defer: 4
2024-06-15 16:44:38,419 DEBUG   HandlerThread:7548 [handler.py:handle_request():146] handle_request: defer
2024-06-15 16:44:38,419 INFO    HandlerThread:7548 [handler.py:handle_request_defer():172] handle defer: 4
2024-06-15 16:44:38,419 DEBUG   SenderThread:7548 [sender.py:send_request():406] send_request: defer
2024-06-15 16:44:38,419 INFO    SenderThread:7548 [sender.py:send_request_defer():610] handle sender defer: 4
2024-06-15 16:44:38,419 INFO    SenderThread:7548 [sender.py:transition_state():614] send defer: 5
2024-06-15 16:44:38,419 DEBUG   HandlerThread:7548 [handler.py:handle_request():146] handle_request: defer
2024-06-15 16:44:38,419 INFO    HandlerThread:7548 [handler.py:handle_request_defer():172] handle defer: 5
2024-06-15 16:44:38,419 DEBUG   SenderThread:7548 [sender.py:send():379] send: summary
2024-06-15 16:44:38,419 INFO    SenderThread:7548 [sender.py:_save_file():1390] saving file wandb-summary.json with policy end
2024-06-15 16:44:38,420 DEBUG   SenderThread:7548 [sender.py:send_request():406] send_request: defer
2024-06-15 16:44:38,420 INFO    SenderThread:7548 [sender.py:send_request_defer():610] handle sender defer: 5
2024-06-15 16:44:38,420 INFO    SenderThread:7548 [sender.py:transition_state():614] send defer: 6
2024-06-15 16:44:38,420 DEBUG   HandlerThread:7548 [handler.py:handle_request():146] handle_request: defer
2024-06-15 16:44:38,420 INFO    HandlerThread:7548 [handler.py:handle_request_defer():172] handle defer: 6
2024-06-15 16:44:38,420 DEBUG   SenderThread:7548 [sender.py:send_request():406] send_request: defer
2024-06-15 16:44:38,420 INFO    SenderThread:7548 [sender.py:send_request_defer():610] handle sender defer: 6
2024-06-15 16:44:38,423 DEBUG   HandlerThread:7548 [handler.py:handle_request():146] handle_request: status_report
2024-06-15 16:44:38,864 INFO    SenderThread:7548 [sender.py:transition_state():614] send defer: 7
2024-06-15 16:44:38,864 DEBUG   HandlerThread:7548 [handler.py:handle_request():146] handle_request: defer
2024-06-15 16:44:38,864 INFO    HandlerThread:7548 [handler.py:handle_request_defer():172] handle defer: 7
2024-06-15 16:44:38,864 DEBUG   SenderThread:7548 [sender.py:send_request():406] send_request: defer
2024-06-15 16:44:38,864 INFO    SenderThread:7548 [sender.py:send_request_defer():610] handle sender defer: 7
2024-06-15 16:44:38,952 INFO    Thread-12 :7548 [dir_watcher.py:_on_file_modified():288] file/dir modified: ./wandb/run-20240615_162823-32urjw61/files/config.yaml
2024-06-15 16:44:38,953 INFO    Thread-12 :7548 [dir_watcher.py:_on_file_created():271] file/dir created: ./wandb/run-20240615_162823-32urjw61/files/wandb-summary.json
2024-06-15 16:44:38,953 INFO    Thread-12 :7548 [dir_watcher.py:_on_file_created():271] file/dir created: ./wandb/run-20240615_162823-32urjw61/files/output.log
2024-06-15 16:44:39,014 DEBUG   HandlerThread:7548 [handler.py:handle_request():146] handle_request: poll_exit
2024-06-15 16:44:40,974 INFO    Thread-12 :7548 [dir_watcher.py:_on_file_modified():288] file/dir modified: ./wandb/run-20240615_162823-32urjw61/files/output.log
2024-06-15 16:44:42,456 INFO    SenderThread:7548 [sender.py:transition_state():614] send defer: 8
2024-06-15 16:44:42,457 DEBUG   SenderThread:7548 [sender.py:send_request():406] send_request: poll_exit
2024-06-15 16:44:42,457 DEBUG   HandlerThread:7548 [handler.py:handle_request():146] handle_request: defer
2024-06-15 16:44:42,457 INFO    HandlerThread:7548 [handler.py:handle_request_defer():172] handle defer: 8
2024-06-15 16:44:42,457 DEBUG   SenderThread:7548 [sender.py:send_request():406] send_request: defer
2024-06-15 16:44:42,457 INFO    SenderThread:7548 [sender.py:send_request_defer():610] handle sender defer: 8
2024-06-15 16:44:42,458 INFO    SenderThread:7548 [job_builder.py:build():318] Attempting to build job artifact
2024-06-15 16:44:42,459 INFO    SenderThread:7548 [job_builder.py:_get_source_type():455] is repo sourced job
2024-06-15 16:44:42,513 INFO    SenderThread:7548 [job_builder.py:build():431] adding wandb-job metadata file
2024-06-15 16:44:42,516 INFO    SenderThread:7548 [sender.py:transition_state():614] send defer: 9
2024-06-15 16:44:42,517 DEBUG   HandlerThread:7548 [handler.py:handle_request():146] handle_request: defer
2024-06-15 16:44:42,517 DEBUG   SenderThread:7548 [sender.py:send():379] send: artifact
2024-06-15 16:44:42,517 INFO    HandlerThread:7548 [handler.py:handle_request_defer():172] handle defer: 9
2024-06-15 16:44:42,986 INFO    Thread-12 :7548 [dir_watcher.py:_on_file_modified():288] file/dir modified: ./wandb/run-20240615_162823-32urjw61/files/output.log
2024-06-15 16:44:43,053 DEBUG   HandlerThread:7548 [handler.py:handle_request():146] handle_request: poll_exit
2024-06-15 16:44:44,385 INFO    SenderThread:7548 [sender.py:send_artifact():1468] sent artifact job-https___github.com_OATML_non-parametric-transformers.git_run.py - {'id': 'QXJ0aWZhY3Q6ODY5NzQ0NzU0', 'state': 'COMMITTED', 'artifactSequence': {'id': 'QXJ0aWZhY3RDb2xsZWN0aW9uOjE1NTU1NjYzOQ==', 'latestArtifact': {'id': 'QXJ0aWZhY3Q6ODY5NzQ0NzU0', 'versionIndex': 6}}}
2024-06-15 16:44:44,386 DEBUG   SenderThread:7548 [sender.py:send_request():406] send_request: defer
2024-06-15 16:44:44,386 DEBUG   HandlerThread:7548 [handler.py:handle_request():146] handle_request: status_report
2024-06-15 16:44:44,387 INFO    SenderThread:7548 [sender.py:send_request_defer():610] handle sender defer: 9
2024-06-15 16:44:44,387 INFO    SenderThread:7548 [dir_watcher.py:finish():358] shutting down directory watcher
2024-06-15 16:44:44,992 INFO    SenderThread:7548 [dir_watcher.py:finish():388] scan: ./wandb/run-20240615_162823-32urjw61/files
2024-06-15 16:44:44,994 INFO    SenderThread:7548 [dir_watcher.py:finish():402] scan save: ./wandb/run-20240615_162823-32urjw61/files/requirements.txt requirements.txt
2024-06-15 16:44:44,994 INFO    SenderThread:7548 [dir_watcher.py:finish():402] scan save: ./wandb/run-20240615_162823-32urjw61/files/output.log output.log
2024-06-15 16:44:45,002 INFO    SenderThread:7548 [dir_watcher.py:finish():402] scan save: ./wandb/run-20240615_162823-32urjw61/files/config.yaml config.yaml
2024-06-15 16:44:45,006 INFO    SenderThread:7548 [dir_watcher.py:finish():402] scan save: ./wandb/run-20240615_162823-32urjw61/files/wandb-summary.json wandb-summary.json
2024-06-15 16:44:45,007 INFO    SenderThread:7548 [dir_watcher.py:finish():402] scan save: ./wandb/run-20240615_162823-32urjw61/files/conda-environment.yaml conda-environment.yaml
2024-06-15 16:44:45,009 INFO    SenderThread:7548 [dir_watcher.py:finish():402] scan save: ./wandb/run-20240615_162823-32urjw61/files/wandb-metadata.json wandb-metadata.json
2024-06-15 16:44:45,010 INFO    SenderThread:7548 [sender.py:transition_state():614] send defer: 10
2024-06-15 16:44:45,010 DEBUG   SenderThread:7548 [sender.py:send_request():406] send_request: poll_exit
2024-06-15 16:44:45,010 DEBUG   HandlerThread:7548 [handler.py:handle_request():146] handle_request: defer
2024-06-15 16:44:45,010 INFO    HandlerThread:7548 [handler.py:handle_request_defer():172] handle defer: 10
2024-06-15 16:44:45,011 DEBUG   SenderThread:7548 [sender.py:send_request():406] send_request: defer
2024-06-15 16:44:45,011 INFO    SenderThread:7548 [sender.py:send_request_defer():610] handle sender defer: 10
2024-06-15 16:44:45,011 INFO    SenderThread:7548 [file_pusher.py:finish():172] shutting down file pusher
2024-06-15 16:44:45,068 DEBUG   HandlerThread:7548 [handler.py:handle_request():146] handle_request: poll_exit
2024-06-15 16:44:45,068 DEBUG   SenderThread:7548 [sender.py:send_request():406] send_request: poll_exit
2024-06-15 16:44:45,772 INFO    wandb-upload_0:7548 [upload_job.py:push():131] Uploaded file ./wandb/run-20240615_162823-32urjw61/files/requirements.txt
2024-06-15 16:44:46,079 DEBUG   HandlerThread:7548 [handler.py:handle_request():146] handle_request: poll_exit
2024-06-15 16:44:46,080 DEBUG   SenderThread:7548 [sender.py:send_request():406] send_request: poll_exit
2024-06-15 16:44:46,329 INFO    wandb-upload_3:7548 [upload_job.py:push():131] Uploaded file ./wandb/run-20240615_162823-32urjw61/files/wandb-summary.json
2024-06-15 16:44:46,329 INFO    wandb-upload_2:7548 [upload_job.py:push():131] Uploaded file ./wandb/run-20240615_162823-32urjw61/files/config.yaml
2024-06-15 16:44:46,329 INFO    wandb-upload_1:7548 [upload_job.py:push():131] Uploaded file ./wandb/run-20240615_162823-32urjw61/files/output.log
2024-06-15 16:44:46,536 INFO    Thread-11 :7548 [sender.py:transition_state():614] send defer: 11
2024-06-15 16:44:46,537 DEBUG   HandlerThread:7548 [handler.py:handle_request():146] handle_request: defer
2024-06-15 16:44:46,537 INFO    HandlerThread:7548 [handler.py:handle_request_defer():172] handle defer: 11
2024-06-15 16:44:46,538 DEBUG   SenderThread:7548 [sender.py:send_request():406] send_request: defer
2024-06-15 16:44:46,538 INFO    SenderThread:7548 [sender.py:send_request_defer():610] handle sender defer: 11
2024-06-15 16:44:46,538 INFO    SenderThread:7548 [file_pusher.py:join():178] waiting for file pusher
2024-06-15 16:44:46,539 INFO    SenderThread:7548 [sender.py:transition_state():614] send defer: 12
2024-06-15 16:44:46,539 DEBUG   HandlerThread:7548 [handler.py:handle_request():146] handle_request: defer
2024-06-15 16:44:46,539 INFO    HandlerThread:7548 [handler.py:handle_request_defer():172] handle defer: 12
2024-06-15 16:44:46,540 DEBUG   SenderThread:7548 [sender.py:send_request():406] send_request: defer
2024-06-15 16:44:46,540 INFO    SenderThread:7548 [sender.py:send_request_defer():610] handle sender defer: 12
2024-06-15 16:44:46,540 INFO    SenderThread:7548 [file_stream.py:finish():614] file stream finish called
2024-06-15 16:44:47,090 DEBUG   HandlerThread:7548 [handler.py:handle_request():146] handle_request: poll_exit
2024-06-15 16:44:47,756 INFO    SenderThread:7548 [file_stream.py:finish():618] file stream finish is done
2024-06-15 16:44:47,757 INFO    SenderThread:7548 [sender.py:transition_state():614] send defer: 13
2024-06-15 16:44:47,757 DEBUG   SenderThread:7548 [sender.py:send_request():406] send_request: poll_exit
2024-06-15 16:44:47,757 DEBUG   HandlerThread:7548 [handler.py:handle_request():146] handle_request: defer
2024-06-15 16:44:47,758 INFO    HandlerThread:7548 [handler.py:handle_request_defer():172] handle defer: 13
2024-06-15 16:44:47,758 DEBUG   SenderThread:7548 [sender.py:send_request():406] send_request: defer
2024-06-15 16:44:47,758 INFO    SenderThread:7548 [sender.py:send_request_defer():610] handle sender defer: 13
2024-06-15 16:44:47,760 INFO    SenderThread:7548 [sender.py:transition_state():614] send defer: 14
2024-06-15 16:44:47,760 DEBUG   HandlerThread:7548 [handler.py:handle_request():146] handle_request: defer
2024-06-15 16:44:47,760 DEBUG   SenderThread:7548 [sender.py:send():379] send: final
2024-06-15 16:44:47,760 INFO    HandlerThread:7548 [handler.py:handle_request_defer():172] handle defer: 14
2024-06-15 16:44:47,760 DEBUG   SenderThread:7548 [sender.py:send():379] send: footer
2024-06-15 16:44:47,760 DEBUG   SenderThread:7548 [sender.py:send_request():406] send_request: defer
2024-06-15 16:44:47,760 INFO    SenderThread:7548 [sender.py:send_request_defer():610] handle sender defer: 14
2024-06-15 16:44:47,761 DEBUG   HandlerThread:7548 [handler.py:handle_request():146] handle_request: poll_exit
2024-06-15 16:44:47,762 DEBUG   SenderThread:7548 [sender.py:send_request():406] send_request: poll_exit
2024-06-15 16:44:47,762 DEBUG   HandlerThread:7548 [handler.py:handle_request():146] handle_request: poll_exit
2024-06-15 16:44:47,763 DEBUG   SenderThread:7548 [sender.py:send_request():406] send_request: poll_exit
2024-06-15 16:44:47,763 DEBUG   HandlerThread:7548 [handler.py:handle_request():146] handle_request: server_info
2024-06-15 16:44:47,763 DEBUG   HandlerThread:7548 [handler.py:handle_request():146] handle_request: get_summary
2024-06-15 16:44:47,764 DEBUG   SenderThread:7548 [sender.py:send_request():406] send_request: server_info
2024-06-15 16:44:47,765 DEBUG   HandlerThread:7548 [handler.py:handle_request():146] handle_request: sampled_history
2024-06-15 16:44:47,766 DEBUG   HandlerThread:7548 [handler.py:handle_request():146] handle_request: internal_messages
2024-06-15 16:44:48,069 INFO    MainThread:7548 [wandb_run.py:_footer_history_summary_info():3920] rendering history
2024-06-15 16:44:48,069 INFO    MainThread:7548 [wandb_run.py:_footer_history_summary_info():3952] rendering summary
2024-06-15 16:44:48,069 INFO    MainThread:7548 [wandb_run.py:_footer_sync_info():3879] logging synced files
2024-06-15 16:44:48,070 DEBUG   HandlerThread:7548 [handler.py:handle_request():146] handle_request: shutdown
2024-06-15 16:44:48,071 INFO    HandlerThread:7548 [handler.py:finish():866] shutting down handler
2024-06-15 16:44:48,774 INFO    WriterThread:7548 [datastore.py:close():296] close: ./wandb/run-20240615_162823-32urjw61/run-32urjw61.wandb
2024-06-15 16:44:49,072 INFO    SenderThread:7548 [sender.py:finish():1546] shutting down sender
2024-06-15 16:44:49,072 INFO    SenderThread:7548 [file_pusher.py:finish():172] shutting down file pusher
2024-06-15 16:44:49,084 INFO    SenderThread:7548 [file_pusher.py:join():178] waiting for file pusher
